"""pyev: typed asynchronous messaging for any Python application."""

from broka.acknowledgements import (
    AcknowledgementAdapter,
    AcknowledgementMode,
    CallbackAcknowledgementAdapter,
)
from broka.broker import Broker, BrokerState, InboundContext, OutboundContext
from broka.capabilities import Capability, CapabilitySet, CapabilitySpec
from broka.config import BrokerConfig, ConfigLoader, SecretValue, load_config
from broka.connection import ConnectionManager, ConnectionState
from broka.deadletter import (
    DeadLetterContext,
    DeadLetterFilter,
    DeadLetterManager,
    DeadLetterPolicy,
    DeadLetterRecord,
    DeadLetterStatus,
    MemoryDeadLetterStore,
    QuarantineManager,
    ReplayManager,
    ReplayOutcome,
    ReplayResult,
)
from broka.delivery import Delivery, DeliveryState, DeliveryTransition
from broka.envelope import CURRENT_ENVELOPE_VERSION, Envelope
from broka.event import (
    EventKey,
    EventMetadata,
    EventRegistry,
    event,
    get_event_metadata,
)
from broka.events import EventEmitter, InternalEvent, InternalEventEmitter
from broka.exceptions import *  # noqa: F403 - exception hierarchy is a public surface
from broka.exceptions import __all__ as _EXCEPTION_EXPORTS
from broka.factory import BrokerFactory
from broka.lifecycle import LifecycleManager, LifecycleState, TaskSupervisor
from broka.message import Message, MessageLike
from broka.middleware import (
    InboundMiddlewarePipeline,
    Middleware,
    MiddlewarePipeline,
    OutboundMiddlewarePipeline,
)
from broka.observability import (
    ComponentHealth,
    HealthReport,
    HealthStatus,
    InMemoryMetrics,
    InMemoryTracer,
    MetricsProvider,
    NoOpMetrics,
    NoOpTracer,
    StructuredLogAdapter,
    TraceContext,
    TracePropagator,
    Tracer,
)
from broka.options import (
    BatchPublishOptions,
    DeliveryMode,
    PublishOptions,
    ReplyOptions,
    RequestOptions,
)
from broka.registry import EngineRegistry, create_default_registry
from broka.reliability import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitState,
    DecorrelatedJitterBackoff,
    EqualJitterBackoff,
    ExponentialBackoff,
    ExponentialFullJitterBackoff,
    FixedBackoff,
    IdempotencyRecord,
    IdempotencyStatus,
    IdempotencyStore,
    LinearBackoff,
    MemoryIdempotencyStore,
    MemoryOutboxStore,
    OutboxDispatcher,
    OutboxMessage,
    OutboxStatus,
    OutboxStore,
    RetryManager,
    RetryPolicy,
)
from broka.results import BatchItemError, BatchPublishResult, PublishResult
from broka.routing import (
    Destination,
    DestinationKind,
    HandlerPattern,
    Route,
    RouteKind,
    Router,
    route_matches,
)
from broka.serialization import (
    DeserializationContext,
    JsonSerializer,
    MessagePackSerializer,
    PickleSerializer,
    SerializationContext,
    Serializer,
    SerializerRegistry,
)
from broka.subscription import Subscription, SubscriptionOptions, SubscriptionState
from broka.typing import Publisher, Subscriber

__version__ = "0.1.0"

# Compatibility spelling only: this is the same runtime, never a competing bus.
EventBus = Broker

__all__ = [
    *_EXCEPTION_EXPORTS,
    "CURRENT_ENVELOPE_VERSION",
    "AcknowledgementAdapter",
    "AcknowledgementMode",
    "BatchItemError",
    "BatchPublishOptions",
    "BatchPublishResult",
    "Broker",
    "BrokerConfig",
    "BrokerFactory",
    "BrokerState",
    "CallbackAcknowledgementAdapter",
    "Capability",
    "CapabilitySet",
    "CapabilitySpec",
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitState",
    "ComponentHealth",
    "ConfigLoader",
    "ConnectionManager",
    "ConnectionState",
    "DeadLetterContext",
    "DeadLetterFilter",
    "DeadLetterManager",
    "DeadLetterPolicy",
    "DeadLetterRecord",
    "DeadLetterStatus",
    "DecorrelatedJitterBackoff",
    "Delivery",
    "DeliveryMode",
    "DeliveryState",
    "DeliveryTransition",
    "DeserializationContext",
    "Destination",
    "DestinationKind",
    "EngineRegistry",
    "Envelope",
    "EqualJitterBackoff",
    "EventBus",
    "EventEmitter",
    "EventKey",
    "EventMetadata",
    "EventRegistry",
    "IdempotencyRecord",
    "IdempotencyStatus",
    "IdempotencyStore",
    "InternalEvent",
    "InternalEventEmitter",
    "ExponentialBackoff",
    "ExponentialFullJitterBackoff",
    "FixedBackoff",
    "HandlerPattern",
    "HealthReport",
    "HealthStatus",
    "InMemoryMetrics",
    "InMemoryTracer",
    "InboundContext",
    "InboundMiddlewarePipeline",
    "JsonSerializer",
    "LifecycleManager",
    "LifecycleState",
    "LinearBackoff",
    "MemoryDeadLetterStore",
    "MemoryIdempotencyStore",
    "MemoryOutboxStore",
    "Message",
    "MessageLike",
    "MessagePackSerializer",
    "MetricsProvider",
    "Middleware",
    "MiddlewarePipeline",
    "NoOpMetrics",
    "NoOpTracer",
    "OutboundContext",
    "OutboundMiddlewarePipeline",
    "OutboxDispatcher",
    "OutboxMessage",
    "OutboxStatus",
    "OutboxStore",
    "PickleSerializer",
    "PublishOptions",
    "PublishResult",
    "Publisher",
    "QuarantineManager",
    "ReplayManager",
    "ReplayOutcome",
    "ReplayResult",
    "ReplyOptions",
    "RequestOptions",
    "RetryManager",
    "RetryPolicy",
    "Route",
    "RouteKind",
    "Router",
    "SecretValue",
    "SerializationContext",
    "Serializer",
    "SerializerRegistry",
    "Subscriber",
    "Subscription",
    "SubscriptionOptions",
    "SubscriptionState",
    "StructuredLogAdapter",
    "TaskSupervisor",
    "TraceContext",
    "TracePropagator",
    "Tracer",
    "create_default_registry",
    "event",
    "get_event_metadata",
    "load_config",
    "route_matches",
]
